version: 1.0.1.{build}

# clone directory
clone_folder: c:\projects\rogueloader

configuration: Release
platform: Any CPU

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  project: Rogueloader.sln
  verbosity: normal

# scripts to run after build
before_build:
  - nuget restore
after_build:
  - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\DarkLoader\bin\Release\RogueLoader.exe
  
